### ISSUE TITLE
How to create a book from pgn?

### ISSUE THREAD

**Issue by fsmosca** [nguyenpham/oobs#1]

**Comment by nguyenpham** [comment]
The project is a tool, run as a console/command line one.

To create an OOBS book, run the program with the command line such as:

```oobs -create -pgn big.png -book big.obs.db3 -cpu 4```

To create a Polyglot book, just rename the extension by .bin:

```oobs -create -pgn big.png -book big.bin -cpu 4```

You may run the program without any argument, it will display the usage/help.
