### ISSUE TITLE
How to make Stockfish create and read this type of opening book?

### ISSUE THREAD

**Issue by taniaMashenko** [nguyenpham/oobs#2]
Hi Nguyen, 
I hope you are doing very well
How to make Stockfish create and read this type of opening book? or at least read

**Comment by nguyenpham** [comment]
A few years ago Stockfish could read and play directly with Polyglot opening books. However, recently it couldn't. All the necessary code (for dealing with opening books) has been removed already.

Now all the opening tasks should be done by chess GUIs (such as Banksia GUI, CuteChess...)
